apiVersion: v2
name: kube-prometheus-stack-homelab
description: Prometheus + Grafana + Alertmanager (kube-prometheus-stack) para o homelab.
type: application
version: 0.1.0
appVersion: "0.92.0"
dependencies:
  - name: kube-prometheus-stack
    version: "87.2.1"
    repository: "https://prometheus-community.github.io/helm-charts"
