apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: WEBPASSWORD
              value: "admin123"
          volumeMounts:
            - name: etc-pihole-volume
              mountPath: "/etc/pihole"
            - name: etc-dnsmasq-volume
              mountPath: "/etc/dnsmasq.d"
      volumes:
        - name: etc-pihole-volume
          hostPath:
            path: /data/pihole/etc-pihole
            type: DirectoryOrCreate
        - name: etc-dnsmasq-volume
          hostPath:
            path: /data/pihole/dnsmasq.d
            type: DirectoryOrCreate
