apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.15.202-192.168.15.210
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.15.201/32
