apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brasleiro01/home-lab/
    targetRevision: HEAD
    path: argocd/namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
