apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: observability
type: Opaque
stringData:
  admin-user: admin
  # Change this password before deploying to production!
  admin-password: "M@rcus2031"
